name: Build

on:
  push:
    branches: [ "master" ]

jobs:

  prepare-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and export
      uses: docker/build-push-action@v5
      with:
        context: .
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: builder-image:latest
        outputs: type=docker,dest=/tmp/builder-image.tar

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: builder-image
        path: /tmp/builder-image.tar
        compression-level: 0


  build-emacs:
    runs-on: ubuntu-latest
    needs: prepare-docker

    strategy:
      matrix:
        source:
          - "{\"name\": \"29.1\", \"tarball\": \"https://ftp.gnu.org/gnu/emacs/emacs-29.1.tar.gz\", \"tarball_dir\": \"emacs-29.1\" }"
        build_with_x11: [ "yes", "no" ]

    steps:
    - name: Install fuse
      run: sudo apt-get install -y fuse libfuse2

    - name: Checkout
      uses: actions/checkout@v4

    - name: Download emacs source from tarball
      run: |
        curl -L ${{ fromJSON(matrix.source).tarball }} | tar xz
        mv ${{ fromJSON(matrix.source).tarball_dir }} emacs-src

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: builder-image
        path: /tmp

    - name: Load image
      run: |
        docker load -i /tmp/builder-image.tar
        docker image ls -a

    - name: Run and package
      run: ./run-and-package.sh builder-image:latest ./emacs-src BUILD_WITH_X11=${{ matrix.build_with_x11 }}

