name: daily-mps
run-name: Daily mps build

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:

  prepare-docker:
    uses: ./.github/workflows/_prepare-docker.yml
    with:
      arch: ${{ matrix.arch }}
    secrets: inherit
    strategy:
      matrix:
        arch:
          - x86_64
          - aarch64

  setup-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Setup vars
        id: setup-vars
        run: |
          echo datetimestr=$(date +%Y%m%d-%H%M) >> $GITHUB_OUTPUT
    outputs:
      datetimestr: ${{ steps.setup-vars.outputs.datetimestr }}

  build-emacs:
    needs:
      - prepare-docker
      - setup-vars

    strategy:
      fail-fast: false
      matrix:
        build_gui:
          - gtk3
          - nox
        arch:
          - x86_64
          - aarch64

    uses: ./.github/workflows/_build-emacs.yml
    with:
      name: mps-${{ matrix.build_native_comp == 'no' && 'no_native_comp' || 'native_comp' }}
      arch: ${{ matrix.arch }}
      branch: feature/igc
      build_gui: ${{ matrix.build_gui }}
      build_native_comp: ${{ matrix.build_native_comp }}
      do_test: false
      do_release: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
      release_name: Daily mps build ${{ needs.setup-vars.outputs.datetimestr }}
      release_latest: false
